// Code generated by protoc-gen-go. DO NOT EDIT.
// source: casbinpb/casbin.proto

package casbinpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnforceRequest struct {
	Params               []string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnforceRequest) Reset()         { *m = EnforceRequest{} }
func (m *EnforceRequest) String() string { return proto.CompactTextString(m) }
func (*EnforceRequest) ProtoMessage()    {}
func (*EnforceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{0}
}

func (m *EnforceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnforceRequest.Unmarshal(m, b)
}
func (m *EnforceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnforceRequest.Marshal(b, m, deterministic)
}
func (m *EnforceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnforceRequest.Merge(m, src)
}
func (m *EnforceRequest) XXX_Size() int {
	return xxx_messageInfo_EnforceRequest.Size(m)
}
func (m *EnforceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnforceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnforceRequest proto.InternalMessageInfo

func (m *EnforceRequest) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type BoolReply struct {
	Res                  bool     `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolReply) Reset()         { *m = BoolReply{} }
func (m *BoolReply) String() string { return proto.CompactTextString(m) }
func (*BoolReply) ProtoMessage()    {}
func (*BoolReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{1}
}

func (m *BoolReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolReply.Unmarshal(m, b)
}
func (m *BoolReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolReply.Marshal(b, m, deterministic)
}
func (m *BoolReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolReply.Merge(m, src)
}
func (m *BoolReply) XXX_Size() int {
	return xxx_messageInfo_BoolReply.Size(m)
}
func (m *BoolReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolReply.DiscardUnknown(m)
}

var xxx_messageInfo_BoolReply proto.InternalMessageInfo

func (m *BoolReply) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{2}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type EmptyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{3}
}

func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (m *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(m, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

type PolicyRequest struct {
	PType                string   `protobuf:"bytes,1,opt,name=pType,proto3" json:"pType,omitempty"`
	Params               []string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyRequest) Reset()         { *m = PolicyRequest{} }
func (m *PolicyRequest) String() string { return proto.CompactTextString(m) }
func (*PolicyRequest) ProtoMessage()    {}
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{4}
}

func (m *PolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyRequest.Unmarshal(m, b)
}
func (m *PolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyRequest.Marshal(b, m, deterministic)
}
func (m *PolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyRequest.Merge(m, src)
}
func (m *PolicyRequest) XXX_Size() int {
	return xxx_messageInfo_PolicyRequest.Size(m)
}
func (m *PolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyRequest proto.InternalMessageInfo

func (m *PolicyRequest) GetPType() string {
	if m != nil {
		return m.PType
	}
	return ""
}

func (m *PolicyRequest) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type SimpleGetRequest struct {
	PType                string   `protobuf:"bytes,1,opt,name=pType,proto3" json:"pType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleGetRequest) Reset()         { *m = SimpleGetRequest{} }
func (m *SimpleGetRequest) String() string { return proto.CompactTextString(m) }
func (*SimpleGetRequest) ProtoMessage()    {}
func (*SimpleGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{5}
}

func (m *SimpleGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleGetRequest.Unmarshal(m, b)
}
func (m *SimpleGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleGetRequest.Marshal(b, m, deterministic)
}
func (m *SimpleGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleGetRequest.Merge(m, src)
}
func (m *SimpleGetRequest) XXX_Size() int {
	return xxx_messageInfo_SimpleGetRequest.Size(m)
}
func (m *SimpleGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleGetRequest proto.InternalMessageInfo

func (m *SimpleGetRequest) GetPType() string {
	if m != nil {
		return m.PType
	}
	return ""
}

type ArrayReply struct {
	Array                []string `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrayReply) Reset()         { *m = ArrayReply{} }
func (m *ArrayReply) String() string { return proto.CompactTextString(m) }
func (*ArrayReply) ProtoMessage()    {}
func (*ArrayReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{6}
}

func (m *ArrayReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayReply.Unmarshal(m, b)
}
func (m *ArrayReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayReply.Marshal(b, m, deterministic)
}
func (m *ArrayReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayReply.Merge(m, src)
}
func (m *ArrayReply) XXX_Size() int {
	return xxx_messageInfo_ArrayReply.Size(m)
}
func (m *ArrayReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayReply.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayReply proto.InternalMessageInfo

func (m *ArrayReply) GetArray() []string {
	if m != nil {
		return m.Array
	}
	return nil
}

type FilteredPolicyRequest struct {
	PType                string   `protobuf:"bytes,1,opt,name=pType,proto3" json:"pType,omitempty"`
	FieldIndex           int32    `protobuf:"varint,2,opt,name=fieldIndex,proto3" json:"fieldIndex,omitempty"`
	FieldValues          []string `protobuf:"bytes,3,rep,name=fieldValues,proto3" json:"fieldValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilteredPolicyRequest) Reset()         { *m = FilteredPolicyRequest{} }
func (m *FilteredPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*FilteredPolicyRequest) ProtoMessage()    {}
func (*FilteredPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{7}
}

func (m *FilteredPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilteredPolicyRequest.Unmarshal(m, b)
}
func (m *FilteredPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilteredPolicyRequest.Marshal(b, m, deterministic)
}
func (m *FilteredPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilteredPolicyRequest.Merge(m, src)
}
func (m *FilteredPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_FilteredPolicyRequest.Size(m)
}
func (m *FilteredPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilteredPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilteredPolicyRequest proto.InternalMessageInfo

func (m *FilteredPolicyRequest) GetPType() string {
	if m != nil {
		return m.PType
	}
	return ""
}

func (m *FilteredPolicyRequest) GetFieldIndex() int32 {
	if m != nil {
		return m.FieldIndex
	}
	return 0
}

func (m *FilteredPolicyRequest) GetFieldValues() []string {
	if m != nil {
		return m.FieldValues
	}
	return nil
}

type UserRoleRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRoleRequest) Reset()         { *m = UserRoleRequest{} }
func (m *UserRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UserRoleRequest) ProtoMessage()    {}
func (*UserRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{8}
}

func (m *UserRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRoleRequest.Unmarshal(m, b)
}
func (m *UserRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRoleRequest.Marshal(b, m, deterministic)
}
func (m *UserRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRoleRequest.Merge(m, src)
}
func (m *UserRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UserRoleRequest.Size(m)
}
func (m *UserRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRoleRequest proto.InternalMessageInfo

func (m *UserRoleRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UserRoleRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type PermissionRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Permissions          []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionRequest) Reset()         { *m = PermissionRequest{} }
func (m *PermissionRequest) String() string { return proto.CompactTextString(m) }
func (*PermissionRequest) ProtoMessage()    {}
func (*PermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{9}
}

func (m *PermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionRequest.Unmarshal(m, b)
}
func (m *PermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionRequest.Marshal(b, m, deterministic)
}
func (m *PermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionRequest.Merge(m, src)
}
func (m *PermissionRequest) XXX_Size() int {
	return xxx_messageInfo_PermissionRequest.Size(m)
}
func (m *PermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionRequest proto.InternalMessageInfo

func (m *PermissionRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PermissionRequest) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type Array2DReply struct {
	D2                   []*Array2DReplyD `protobuf:"bytes,1,rep,name=d2,proto3" json:"d2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Array2DReply) Reset()         { *m = Array2DReply{} }
func (m *Array2DReply) String() string { return proto.CompactTextString(m) }
func (*Array2DReply) ProtoMessage()    {}
func (*Array2DReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{10}
}

func (m *Array2DReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Array2DReply.Unmarshal(m, b)
}
func (m *Array2DReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Array2DReply.Marshal(b, m, deterministic)
}
func (m *Array2DReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Array2DReply.Merge(m, src)
}
func (m *Array2DReply) XXX_Size() int {
	return xxx_messageInfo_Array2DReply.Size(m)
}
func (m *Array2DReply) XXX_DiscardUnknown() {
	xxx_messageInfo_Array2DReply.DiscardUnknown(m)
}

var xxx_messageInfo_Array2DReply proto.InternalMessageInfo

func (m *Array2DReply) GetD2() []*Array2DReplyD {
	if m != nil {
		return m.D2
	}
	return nil
}

type Array2DReplyD struct {
	D1                   []string `protobuf:"bytes,1,rep,name=d1,proto3" json:"d1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Array2DReplyD) Reset()         { *m = Array2DReplyD{} }
func (m *Array2DReplyD) String() string { return proto.CompactTextString(m) }
func (*Array2DReplyD) ProtoMessage()    {}
func (*Array2DReplyD) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0e3c069f9136b8, []int{10, 0}
}

func (m *Array2DReplyD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Array2DReplyD.Unmarshal(m, b)
}
func (m *Array2DReplyD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Array2DReplyD.Marshal(b, m, deterministic)
}
func (m *Array2DReplyD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Array2DReplyD.Merge(m, src)
}
func (m *Array2DReplyD) XXX_Size() int {
	return xxx_messageInfo_Array2DReplyD.Size(m)
}
func (m *Array2DReplyD) XXX_DiscardUnknown() {
	xxx_messageInfo_Array2DReplyD.DiscardUnknown(m)
}

var xxx_messageInfo_Array2DReplyD proto.InternalMessageInfo

func (m *Array2DReplyD) GetD1() []string {
	if m != nil {
		return m.D1
	}
	return nil
}

func init() {
	proto.RegisterType((*EnforceRequest)(nil), "casbinpb.EnforceRequest")
	proto.RegisterType((*BoolReply)(nil), "casbinpb.BoolReply")
	proto.RegisterType((*EmptyRequest)(nil), "casbinpb.EmptyRequest")
	proto.RegisterType((*EmptyReply)(nil), "casbinpb.EmptyReply")
	proto.RegisterType((*PolicyRequest)(nil), "casbinpb.PolicyRequest")
	proto.RegisterType((*SimpleGetRequest)(nil), "casbinpb.SimpleGetRequest")
	proto.RegisterType((*ArrayReply)(nil), "casbinpb.ArrayReply")
	proto.RegisterType((*FilteredPolicyRequest)(nil), "casbinpb.FilteredPolicyRequest")
	proto.RegisterType((*UserRoleRequest)(nil), "casbinpb.UserRoleRequest")
	proto.RegisterType((*PermissionRequest)(nil), "casbinpb.PermissionRequest")
	proto.RegisterType((*Array2DReply)(nil), "casbinpb.Array2DReply")
	proto.RegisterType((*Array2DReplyD)(nil), "casbinpb.Array2DReply.d")
}

func init() { proto.RegisterFile("casbinpb/casbin.proto", fileDescriptor_1b0e3c069f9136b8) }

var fileDescriptor_1b0e3c069f9136b8 = []byte{
	// 700 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x97, 0x5f, 0x73, 0xd2, 0x40,
	0x14, 0xc5, 0x0b, 0xb5, 0xb5, 0x39, 0x50, 0x2c, 0x4b, 0x8b, 0x94, 0xd1, 0x8a, 0x79, 0xe2, 0x09,
	0xa7, 0xf8, 0xa4, 0xb5, 0x5a, 0x5a, 0x5b, 0xe8, 0x54, 0xdb, 0x4e, 0xd0, 0x3e, 0xd8, 0xa7, 0xc0,
	0x6e, 0x9d, 0x38, 0x81, 0x8d, 0xd9, 0xe0, 0xc8, 0x77, 0xf6, 0x43, 0x38, 0x6c, 0xfe, 0x10, 0xb0,
	0xa9, 0x24, 0xe1, 0x6d, 0x77, 0x73, 0xef, 0xef, 0x9e, 0xdc, 0x9c, 0x4d, 0x36, 0xd8, 0xe9, 0xeb,
	0xa2, 0x67, 0x0c, 0xad, 0xde, 0x2b, 0x77, 0xd0, 0xb0, 0x6c, 0xee, 0x70, 0xb2, 0xe1, 0x2f, 0xab,
	0x75, 0x14, 0x4e, 0x87, 0x77, 0xdc, 0xee, 0x33, 0x8d, 0xfd, 0x1c, 0x31, 0xe1, 0x90, 0x32, 0xd6,
	0x2d, 0xdd, 0xd6, 0x07, 0xa2, 0x92, 0xad, 0xad, 0xd6, 0x15, 0xcd, 0x9b, 0xa9, 0xcf, 0xa1, 0x1c,
	0x73, 0x6e, 0x6a, 0xcc, 0x32, 0xc7, 0x64, 0x0b, 0xab, 0x36, 0x13, 0x95, 0x4c, 0x2d, 0x53, 0xdf,
	0xd0, 0x26, 0x43, 0xb5, 0x80, 0xfc, 0xe9, 0xc0, 0x72, 0xc6, 0x1e, 0x46, 0xcd, 0x03, 0xde, 0xdc,
	0x32, 0xc7, 0xea, 0x21, 0x36, 0xaf, 0xb9, 0x69, 0xf4, 0xfd, 0xcb, 0x64, 0x1b, 0x6b, 0xd6, 0x97,
	0xb1, 0xc5, 0x24, 0x42, 0xd1, 0xdc, 0x49, 0x64, 0xed, 0x3a, 0xb6, 0xba, 0xc6, 0xc0, 0x32, 0x59,
	0x9b, 0x39, 0x0f, 0x12, 0x54, 0x15, 0x68, 0xd9, 0xb6, 0xee, 0x96, 0x9d, 0xc4, 0xe8, 0x93, 0x59,
	0x25, 0x23, 0x71, 0xee, 0x44, 0xe5, 0xd8, 0x39, 0x33, 0x4c, 0x87, 0xd9, 0x8c, 0x2e, 0x22, 0x6a,
	0x0f, 0xb8, 0x33, 0x98, 0x49, 0xcf, 0x87, 0x94, 0xfd, 0xae, 0x64, 0x6b, 0x99, 0xfa, 0x9a, 0x16,
	0x5a, 0x21, 0x35, 0xe4, 0xe4, 0xec, 0x46, 0x37, 0x47, 0x4c, 0x54, 0x56, 0x65, 0xa9, 0xf0, 0x92,
	0xfa, 0x06, 0x4f, 0xbe, 0x0a, 0x66, 0x6b, 0xdc, 0x0c, 0xba, 0x4c, 0xf0, 0x68, 0x24, 0x98, 0xed,
	0x55, 0x92, 0xe3, 0xc9, 0x9a, 0xcd, 0x4d, 0x26, 0x4b, 0x28, 0x9a, 0x1c, 0xab, 0xe7, 0x28, 0x5e,
	0x33, 0x7b, 0x60, 0x08, 0x61, 0xf0, 0xe1, 0x43, 0xc9, 0x35, 0xe4, 0xac, 0x20, 0xd0, 0xef, 0x5f,
	0x78, 0x49, 0xfd, 0x8c, 0xbc, 0x6c, 0x4d, 0xf3, 0xa3, 0xdb, 0x9c, 0x3a, 0xb2, 0xb4, 0x29, 0x3b,
	0x93, 0x6b, 0x56, 0x1a, 0xbe, 0x23, 0x1a, 0xe1, 0x98, 0x06, 0xd5, 0xb2, 0xb4, 0x59, 0x2d, 0x21,
	0x43, 0x49, 0x01, 0x59, 0xba, 0xef, 0x35, 0x32, 0x4b, 0xf7, 0x9b, 0x7f, 0x4a, 0x58, 0x3f, 0x91,
	0x49, 0xe4, 0x2d, 0x1e, 0x7b, 0x26, 0x22, 0x21, 0xd0, 0xac, 0xaf, 0xaa, 0xa5, 0xe9, 0x95, 0xc0,
	0x47, 0xea, 0x0a, 0x79, 0x07, 0x7c, 0xe2, 0xba, 0xf7, 0x20, 0x48, 0x39, 0x94, 0x1e, 0x72, 0x53,
	0x75, 0xfb, 0x9f, 0xf5, 0x20, 0xbb, 0xab, 0xff, 0x62, 0x09, 0xb3, 0x0f, 0xa0, 0xb4, 0xa8, 0x5f,
	0xfa, 0xe9, 0x34, 0x68, 0xc6, 0x15, 0x51, 0xc2, 0x8f, 0x50, 0x68, 0x51, 0x7a, 0xa9, 0x0f, 0x58,
	0x52, 0xc2, 0x7b, 0xe4, 0x35, 0x36, 0xe0, 0x81, 0xfc, 0xb8, 0xf9, 0x27, 0x28, 0xba, 0xf9, 0x69,
	0x44, 0x5c, 0x62, 0xdb, 0x85, 0xcc, 0x6e, 0x09, 0xf2, 0x62, 0x1a, 0x7e, 0xef, 0x66, 0x89, 0xe2,
	0x75, 0xb1, 0x3b, 0xcb, 0x0b, 0x8b, 0x4b, 0x0a, 0x3d, 0x84, 0xd2, 0x66, 0xce, 0x7f, 0x9e, 0x72,
	0xf9, 0x7e, 0x0f, 0xcb, 0x46, 0x15, 0xda, 0xcc, 0x59, 0xa8, 0x4b, 0xd1, 0x90, 0x4b, 0x14, 0xdb,
	0xcc, 0x89, 0xdb, 0xa5, 0x68, 0x5e, 0x17, 0xe5, 0x10, 0x2f, 0x56, 0x97, 0x1e, 0xba, 0xd3, 0x62,
	0x8b, 0xd2, 0xb6, 0xcd, 0x47, 0x96, 0x31, 0xfc, 0x9e, 0xd0, 0x12, 0x1d, 0x94, 0x7d, 0x67, 0xa7,
	0x24, 0x9d, 0xf9, 0xe6, 0x4a, 0xc9, 0xb9, 0xf0, 0x4d, 0xb5, 0x0c, 0x51, 0x37, 0x78, 0x36, 0xeb,
	0xd0, 0x39, 0x5e, 0x52, 0x93, 0xde, 0xe2, 0xe5, 0x3d, 0xce, 0x5f, 0x12, 0xfc, 0x54, 0xba, 0x6f,
	0x0e, 0x16, 0x7f, 0x27, 0x5c, 0x48, 0xd3, 0xc5, 0xea, 0x62, 0x34, 0xec, 0x06, 0xbb, 0x21, 0x07,
	0xc7, 0xbd, 0xd1, 0x68, 0xee, 0x2d, 0xf6, 0xe6, 0x77, 0xc6, 0xf2, 0xe0, 0x47, 0xf2, 0x5d, 0xd0,
	0x32, 0xcd, 0xee, 0xa8, 0xf7, 0x83, 0xf5, 0x1d, 0xb1, 0xc8, 0x57, 0x63, 0x7a, 0xa4, 0x50, 0x57,
	0xc8, 0x39, 0x4a, 0x2e, 0x41, 0x2a, 0x0b, 0x30, 0xd5, 0x69, 0xf8, 0xfc, 0x59, 0x25, 0x12, 0xf5,
	0x01, 0x9b, 0x2e, 0xea, 0x2a, 0xa1, 0x96, 0x0e, 0x48, 0x48, 0xcb, 0xd5, 0x32, 0xa4, 0xb4, 0xfa,
	0xce, 0xe4, 0xb8, 0x90, 0x52, 0x8a, 0x4f, 0x49, 0x22, 0xe5, 0x10, 0x39, 0x97, 0x34, 0x39, 0x30,
	0xc5, 0x17, 0x72, 0x86, 0xad, 0x90, 0x10, 0x97, 0x91, 0x44, 0xc6, 0x01, 0x94, 0x8e, 0x2e, 0x92,
	0x9f, 0x0e, 0x3a, 0xba, 0x48, 0xf3, 0x61, 0x3e, 0x41, 0xb1, 0xa3, 0x8b, 0xf4, 0xaf, 0x72, 0x5f,
	0x46, 0x3a, 0xd2, 0x31, 0xbe, 0x05, 0x3f, 0x0d, 0xbd, 0x75, 0xf9, 0x17, 0xf1, 0xfa, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe5, 0x9e, 0x09, 0x28, 0x5e, 0x0c, 0x00, 0x00,
}
